[package]
name = "d02"
version = "0.1.0"
authors = ["Mathieu Lemay <mathieu.lemay@broadsign.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
