[package]
name = "d09"
version = "0.1.0"
authors = ["Mathieu Lemay <acidrain1@gmail.com>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
intcode = { path = "../intcode" }
